S2-I06
TerryIsmael/Acme-L3-D02 pull request #93
Opened 2023-03-13 18:36 UTC by virolialo

2023-03-14 12:33 UTC, TerryIsmael commented on src/main/java/acme/entities/activity/Activity.java
> +
Falta NotNull

2023-03-14 12:36 UTC, TerryIsmael commented on src/main/java/acme/entities/activity/Activity.java
> +
Falta NotNull

2023-03-14 12:53 UTC, virolialo commented on src/main/java/acme/entities/activity/Activity.java
> +public class Activity extends AbstractRole {
Correción hecha

2023-03-14 12:54 UTC, virolialo commented on src/main/java/acme/entities/activity/Activity.java
> +
Corrección hecha

2023-03-14 12:55 UTC, virolialo commented on src/main/java/acme/entities/activity/Activity.java
> +	@ManyToOne(optional = false)
Etiquetas Valid y NotNull añadidas a la relación de la entidad

2023-03-14 12:56 UTC, virolialo commented on src/main/java/acme/entities/activity/Activity.java
> +
Eliminadas las etiquetas NotBlank y Length (no eran validas ya que se trata de un enum) y sustituidas por un NotNull

2023-03-14 16:50 UTC, TerryIsmael requested changes
Modificar lo comentado.

2023-03-14 16:50 UTC, TerryIsmael commented on src/main/java/acme/entities/activity/Activity.java
> +	@ManyToOne(optional = false)
Ahora falta la etiqueta @ManyToOne. Cambiar "wordbook", que está mal escrito, por enrolment, ya que la relación no es un workbook como tal

2023-03-15 12:50 UTC, virolialo commented on src/main/java/acme/entities/activity/Activity.java
> +	@ManyToOne(optional = false)
Nombre del atributo cambiado a enrolment

2023-03-15 16:49 UTC, TerryIsmael commented on src/main/java/acme/entities/activity/Activity.java
> +	protected String			abstracts;
Cambiar atributo description por abstraction para seguir un lenguaje más adecuado con el del cliente

2023-03-15 17:06 UTC, TerryIsmael approved these changes
All in order.

2023-03-15 17:06 UTC, merged